/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignRouteImport } from './routes/sign'
import { Route as PlayRouteImport } from './routes/play'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AllianceRouteImport } from './routes/alliance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUserRegisterReferralRouteImport } from './routes/api/user.register-referral'
import { Route as ApiUserProfileRouteImport } from './routes/api/user.profile'
import { Route as ApiUserConvertCoinsRouteImport } from './routes/api/user.convert-coins'
import { Route as ApiUserClaimWelcomeGiftRouteImport } from './routes/api/user.claim-welcome-gift'
import { Route as ApiUserClaimAllianceRewardsRouteImport } from './routes/api/user.claim-alliance-rewards'
import { Route as ApiMinigameBetAccumulatorRouteImport } from './routes/api/minigame.bet-accumulator'
import { Route as ApiMinigameBetRouteImport } from './routes/api/minigame.bet'
import { Route as ApiMatchesUpdateResultRouteImport } from './routes/api/matches.update-result'
import { Route as ApiMatchesCurrentRouteImport } from './routes/api/matches.current'
import { Route as ApiMatchesCreateRouteImport } from './routes/api/matches.create'
import { Route as ApiLeaguesStandingsRouteImport } from './routes/api/leagues.standings'
import { Route as ApiCouponsVerifyRouteImport } from './routes/api/coupons.verify'
import { Route as ApiBetsSettleRouteImport } from './routes/api/bets.settle'
import { Route as ApiBetsActiveRouteImport } from './routes/api/bets.active'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AllianceRoute = AllianceRouteImport.update({
  id: '/alliance',
  path: '/alliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserRegisterReferralRoute = ApiUserRegisterReferralRouteImport.update({
  id: '/api/user/register-referral',
  path: '/api/user/register-referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: '/api/user/profile',
  path: '/api/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserConvertCoinsRoute = ApiUserConvertCoinsRouteImport.update({
  id: '/api/user/convert-coins',
  path: '/api/user/convert-coins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserClaimWelcomeGiftRoute = ApiUserClaimWelcomeGiftRouteImport.update({
  id: '/api/user/claim-welcome-gift',
  path: '/api/user/claim-welcome-gift',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserClaimAllianceRewardsRoute =
  ApiUserClaimAllianceRewardsRouteImport.update({
    id: '/api/user/claim-alliance-rewards',
    path: '/api/user/claim-alliance-rewards',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMinigameBetAccumulatorRoute =
  ApiMinigameBetAccumulatorRouteImport.update({
    id: '/api/minigame/bet-accumulator',
    path: '/api/minigame/bet-accumulator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMinigameBetRoute = ApiMinigameBetRouteImport.update({
  id: '/api/minigame/bet',
  path: '/api/minigame/bet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesUpdateResultRoute = ApiMatchesUpdateResultRouteImport.update({
  id: '/api/matches/update-result',
  path: '/api/matches/update-result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesCurrentRoute = ApiMatchesCurrentRouteImport.update({
  id: '/api/matches/current',
  path: '/api/matches/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMatchesCreateRoute = ApiMatchesCreateRouteImport.update({
  id: '/api/matches/create',
  path: '/api/matches/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaguesStandingsRoute = ApiLeaguesStandingsRouteImport.update({
  id: '/api/leagues/standings',
  path: '/api/leagues/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCouponsVerifyRoute = ApiCouponsVerifyRouteImport.update({
  id: '/api/coupons/verify',
  path: '/api/coupons/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetsSettleRoute = ApiBetsSettleRouteImport.update({
  id: '/api/bets/settle',
  path: '/api/bets/settle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBetsActiveRoute = ApiBetsActiveRouteImport.update({
  id: '/api/bets/active',
  path: '/api/bets/active',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alliance': typeof AllianceRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/entry': typeof EntryRoute
  '/onboarding': typeof OnboardingRoute
  '/play': typeof PlayRoute
  '/sign': typeof SignRoute
  '/welcome': typeof WelcomeRoute
  '/api/bets/active': typeof ApiBetsActiveRoute
  '/api/bets/settle': typeof ApiBetsSettleRoute
  '/api/coupons/verify': typeof ApiCouponsVerifyRoute
  '/api/leagues/standings': typeof ApiLeaguesStandingsRoute
  '/api/matches/create': typeof ApiMatchesCreateRoute
  '/api/matches/current': typeof ApiMatchesCurrentRoute
  '/api/matches/update-result': typeof ApiMatchesUpdateResultRoute
  '/api/minigame/bet': typeof ApiMinigameBetRoute
  '/api/minigame/bet-accumulator': typeof ApiMinigameBetAccumulatorRoute
  '/api/user/claim-alliance-rewards': typeof ApiUserClaimAllianceRewardsRoute
  '/api/user/claim-welcome-gift': typeof ApiUserClaimWelcomeGiftRoute
  '/api/user/convert-coins': typeof ApiUserConvertCoinsRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/register-referral': typeof ApiUserRegisterReferralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alliance': typeof AllianceRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/entry': typeof EntryRoute
  '/onboarding': typeof OnboardingRoute
  '/play': typeof PlayRoute
  '/sign': typeof SignRoute
  '/welcome': typeof WelcomeRoute
  '/api/bets/active': typeof ApiBetsActiveRoute
  '/api/bets/settle': typeof ApiBetsSettleRoute
  '/api/coupons/verify': typeof ApiCouponsVerifyRoute
  '/api/leagues/standings': typeof ApiLeaguesStandingsRoute
  '/api/matches/create': typeof ApiMatchesCreateRoute
  '/api/matches/current': typeof ApiMatchesCurrentRoute
  '/api/matches/update-result': typeof ApiMatchesUpdateResultRoute
  '/api/minigame/bet': typeof ApiMinigameBetRoute
  '/api/minigame/bet-accumulator': typeof ApiMinigameBetAccumulatorRoute
  '/api/user/claim-alliance-rewards': typeof ApiUserClaimAllianceRewardsRoute
  '/api/user/claim-welcome-gift': typeof ApiUserClaimWelcomeGiftRoute
  '/api/user/convert-coins': typeof ApiUserConvertCoinsRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/register-referral': typeof ApiUserRegisterReferralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alliance': typeof AllianceRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/entry': typeof EntryRoute
  '/onboarding': typeof OnboardingRoute
  '/play': typeof PlayRoute
  '/sign': typeof SignRoute
  '/welcome': typeof WelcomeRoute
  '/api/bets/active': typeof ApiBetsActiveRoute
  '/api/bets/settle': typeof ApiBetsSettleRoute
  '/api/coupons/verify': typeof ApiCouponsVerifyRoute
  '/api/leagues/standings': typeof ApiLeaguesStandingsRoute
  '/api/matches/create': typeof ApiMatchesCreateRoute
  '/api/matches/current': typeof ApiMatchesCurrentRoute
  '/api/matches/update-result': typeof ApiMatchesUpdateResultRoute
  '/api/minigame/bet': typeof ApiMinigameBetRoute
  '/api/minigame/bet-accumulator': typeof ApiMinigameBetAccumulatorRoute
  '/api/user/claim-alliance-rewards': typeof ApiUserClaimAllianceRewardsRoute
  '/api/user/claim-welcome-gift': typeof ApiUserClaimWelcomeGiftRoute
  '/api/user/convert-coins': typeof ApiUserConvertCoinsRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/user/register-referral': typeof ApiUserRegisterReferralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alliance'
    | '/connect'
    | '/dashboard'
    | '/entry'
    | '/onboarding'
    | '/play'
    | '/sign'
    | '/welcome'
    | '/api/bets/active'
    | '/api/bets/settle'
    | '/api/coupons/verify'
    | '/api/leagues/standings'
    | '/api/matches/create'
    | '/api/matches/current'
    | '/api/matches/update-result'
    | '/api/minigame/bet'
    | '/api/minigame/bet-accumulator'
    | '/api/user/claim-alliance-rewards'
    | '/api/user/claim-welcome-gift'
    | '/api/user/convert-coins'
    | '/api/user/profile'
    | '/api/user/register-referral'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alliance'
    | '/connect'
    | '/dashboard'
    | '/entry'
    | '/onboarding'
    | '/play'
    | '/sign'
    | '/welcome'
    | '/api/bets/active'
    | '/api/bets/settle'
    | '/api/coupons/verify'
    | '/api/leagues/standings'
    | '/api/matches/create'
    | '/api/matches/current'
    | '/api/matches/update-result'
    | '/api/minigame/bet'
    | '/api/minigame/bet-accumulator'
    | '/api/user/claim-alliance-rewards'
    | '/api/user/claim-welcome-gift'
    | '/api/user/convert-coins'
    | '/api/user/profile'
    | '/api/user/register-referral'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alliance'
    | '/connect'
    | '/dashboard'
    | '/entry'
    | '/onboarding'
    | '/play'
    | '/sign'
    | '/welcome'
    | '/api/bets/active'
    | '/api/bets/settle'
    | '/api/coupons/verify'
    | '/api/leagues/standings'
    | '/api/matches/create'
    | '/api/matches/current'
    | '/api/matches/update-result'
    | '/api/minigame/bet'
    | '/api/minigame/bet-accumulator'
    | '/api/user/claim-alliance-rewards'
    | '/api/user/claim-welcome-gift'
    | '/api/user/convert-coins'
    | '/api/user/profile'
    | '/api/user/register-referral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AllianceRoute: typeof AllianceRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  EntryRoute: typeof EntryRoute
  OnboardingRoute: typeof OnboardingRoute
  PlayRoute: typeof PlayRoute
  SignRoute: typeof SignRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiBetsActiveRoute: typeof ApiBetsActiveRoute
  ApiBetsSettleRoute: typeof ApiBetsSettleRoute
  ApiCouponsVerifyRoute: typeof ApiCouponsVerifyRoute
  ApiLeaguesStandingsRoute: typeof ApiLeaguesStandingsRoute
  ApiMatchesCreateRoute: typeof ApiMatchesCreateRoute
  ApiMatchesCurrentRoute: typeof ApiMatchesCurrentRoute
  ApiMatchesUpdateResultRoute: typeof ApiMatchesUpdateResultRoute
  ApiMinigameBetRoute: typeof ApiMinigameBetRoute
  ApiMinigameBetAccumulatorRoute: typeof ApiMinigameBetAccumulatorRoute
  ApiUserClaimAllianceRewardsRoute: typeof ApiUserClaimAllianceRewardsRoute
  ApiUserClaimWelcomeGiftRoute: typeof ApiUserClaimWelcomeGiftRoute
  ApiUserConvertCoinsRoute: typeof ApiUserConvertCoinsRoute
  ApiUserProfileRoute: typeof ApiUserProfileRoute
  ApiUserRegisterReferralRoute: typeof ApiUserRegisterReferralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alliance': {
      id: '/alliance'
      path: '/alliance'
      fullPath: '/alliance'
      preLoaderRoute: typeof AllianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/register-referral': {
      id: '/api/user/register-referral'
      path: '/api/user/register-referral'
      fullPath: '/api/user/register-referral'
      preLoaderRoute: typeof ApiUserRegisterReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/profile': {
      id: '/api/user/profile'
      path: '/api/user/profile'
      fullPath: '/api/user/profile'
      preLoaderRoute: typeof ApiUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/convert-coins': {
      id: '/api/user/convert-coins'
      path: '/api/user/convert-coins'
      fullPath: '/api/user/convert-coins'
      preLoaderRoute: typeof ApiUserConvertCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/claim-welcome-gift': {
      id: '/api/user/claim-welcome-gift'
      path: '/api/user/claim-welcome-gift'
      fullPath: '/api/user/claim-welcome-gift'
      preLoaderRoute: typeof ApiUserClaimWelcomeGiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/claim-alliance-rewards': {
      id: '/api/user/claim-alliance-rewards'
      path: '/api/user/claim-alliance-rewards'
      fullPath: '/api/user/claim-alliance-rewards'
      preLoaderRoute: typeof ApiUserClaimAllianceRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/minigame/bet-accumulator': {
      id: '/api/minigame/bet-accumulator'
      path: '/api/minigame/bet-accumulator'
      fullPath: '/api/minigame/bet-accumulator'
      preLoaderRoute: typeof ApiMinigameBetAccumulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/minigame/bet': {
      id: '/api/minigame/bet'
      path: '/api/minigame/bet'
      fullPath: '/api/minigame/bet'
      preLoaderRoute: typeof ApiMinigameBetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/update-result': {
      id: '/api/matches/update-result'
      path: '/api/matches/update-result'
      fullPath: '/api/matches/update-result'
      preLoaderRoute: typeof ApiMatchesUpdateResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/current': {
      id: '/api/matches/current'
      path: '/api/matches/current'
      fullPath: '/api/matches/current'
      preLoaderRoute: typeof ApiMatchesCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/matches/create': {
      id: '/api/matches/create'
      path: '/api/matches/create'
      fullPath: '/api/matches/create'
      preLoaderRoute: typeof ApiMatchesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leagues/standings': {
      id: '/api/leagues/standings'
      path: '/api/leagues/standings'
      fullPath: '/api/leagues/standings'
      preLoaderRoute: typeof ApiLeaguesStandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coupons/verify': {
      id: '/api/coupons/verify'
      path: '/api/coupons/verify'
      fullPath: '/api/coupons/verify'
      preLoaderRoute: typeof ApiCouponsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bets/settle': {
      id: '/api/bets/settle'
      path: '/api/bets/settle'
      fullPath: '/api/bets/settle'
      preLoaderRoute: typeof ApiBetsSettleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bets/active': {
      id: '/api/bets/active'
      path: '/api/bets/active'
      fullPath: '/api/bets/active'
      preLoaderRoute: typeof ApiBetsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AllianceRoute: AllianceRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  EntryRoute: EntryRoute,
  OnboardingRoute: OnboardingRoute,
  PlayRoute: PlayRoute,
  SignRoute: SignRoute,
  WelcomeRoute: WelcomeRoute,
  ApiBetsActiveRoute: ApiBetsActiveRoute,
  ApiBetsSettleRoute: ApiBetsSettleRoute,
  ApiCouponsVerifyRoute: ApiCouponsVerifyRoute,
  ApiLeaguesStandingsRoute: ApiLeaguesStandingsRoute,
  ApiMatchesCreateRoute: ApiMatchesCreateRoute,
  ApiMatchesCurrentRoute: ApiMatchesCurrentRoute,
  ApiMatchesUpdateResultRoute: ApiMatchesUpdateResultRoute,
  ApiMinigameBetRoute: ApiMinigameBetRoute,
  ApiMinigameBetAccumulatorRoute: ApiMinigameBetAccumulatorRoute,
  ApiUserClaimAllianceRewardsRoute: ApiUserClaimAllianceRewardsRoute,
  ApiUserClaimWelcomeGiftRoute: ApiUserClaimWelcomeGiftRoute,
  ApiUserConvertCoinsRoute: ApiUserConvertCoinsRoute,
  ApiUserProfileRoute: ApiUserProfileRoute,
  ApiUserRegisterReferralRoute: ApiUserRegisterReferralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
